Angular 15 and Webpack 5 upgrade
vmware/vcd-ext-sdk pull request #273
Opened 2023-05-09 13:34 UTC by nvladimirovi

2023-05-12 12:49 UTC, stoychevl requested changes
We need to come up with a solution for handling API Client Negotiated versions, because currently the hardcoded versions in the client lack behind the new VCD API versions. This will cause some plugins in the future to fail. We have two approaches:

- Maintain the Supported versions list 
- Always chose highest supported API version from api/versions response

The current implementation of "actAs()" method, doesn't return a clone of the VCD Api client, but rather a mutated reference of the client. This makes every consecutive call of the original client to use the latest set context. We can:

- actAs() returns a copy of the vcdApi client with the changed context
- pass actAs as a optional property of the CRUD http functions in the service

The current implementation of setVersion can only be used after the initialisation of the apiClient, thus the client always uses the negotiated maximum version for the initial API session calls.

- Pass apiClient version from service init()
- Pass apiClient version via .forRoot() in the SKD module.

2023-05-12 13:14 UTC, stoychevl commented on packages/angular/projects/vcd/plugin-builders/src/lib/base/index.ts
> +        if (options.enableRuntimeDependecyManagement) {
Please fix the type enableRuntimeDependecyManagement -> enableRuntimeDependencyManagement

2023-05-12 13:32 UTC, stoychevl commented
We need to come up with a solution for handling API Client Negotiated versions, because currently the hardcoded versions in the client lack behind the new VCD API versions. This will cause some plugins in the future to fail.

2023-05-12 13:36 UTC, stoychevl approved these changes
It all makes sense, however we also need to delete all legacy vcd-ext CLI related code and the CARE package implementation.

2023-05-16 11:20 UTC, iilieva approved these changes

2023-05-16 11:20 UTC, iilieva commented on packages/plugin-builders/README.md
> +We implement it in the standard Angular documented way,
This information is redundant.

2023-05-16 11:20 UTC, iilieva commented on packages/plugin-builders/README.md
> +All npm dependencis in the `externals` list will be provided to your UI Plugin by VMware Cloud Director at runtime, this boosts the loading time of your UI Plugin a lot.
nit: a lot -> significantly

2023-05-16 11:20 UTC, iilieva commented on packages/plugin-builders/README.md
> +We leverage Webpack's `DefinePlugin`, to replace keywords in the final JS bundle. Most often we use to perform JS isolation in special type of UI Plguins called Hyper. Regular UI Plugins doesn't leve
nit: doesn't -> do not

2023-05-16 11:20 UTC, iilieva commented on packages/plugin-builders/README.md
> +Now, the PostCSS Plugins are not used by the Regular UI Plugins in build time, it's used only by the Hyper ones.
nit: The PostCss plugins are used at build time only by the Hyper plugins. The regular UI plugins do not utilize them.

2023-05-16 11:20 UTC, iilieva commented on packages/plugin-builders/package.json
> +    "@angular-devkit/build-angular": "^15.0.0",
The same suggestions for fixed versions here.

2023-05-16 12:57 UTC, irahov approved these changes

2023-05-19 07:09 UTC, nvladimirovi commented on packages/angular/package.json
> +  "version": "0.0.0",
That is not the package version, this is a version that isn't used by NPM or anything other, that's just the "holder" project.

2023-05-19 07:26 UTC, nvladimirovi commented on packages/angular/projects/vcd/sdk/src/client/client/vcd.api.client.spec.data.ts
> +        },
This is a test that we don't run currently, we'll need to implement new ones, or refactor the old.

2023-05-31 05:59 UTC, merged